version: '3.8'

services:
  # 🔹 FRONTEND - Blue
  frontend_blue:
    image: junaiddocker743/greenx-frontend:latest
    container_name: frontend_blue
    ports:
      - "3001:3000"   # Blue alag port par chalega
    depends_on:
      - backend_blue

  # 🔹 BACKEND - Blue
  backend_blue:
    image: junaiddocker743/greenx-backend:latest
    container_name: backend_blue
    environment:
      ENV: dev
      DB: mysql
      DB_USER: root
      DB_PASSWORD: passdb0127
      DB_HOST: db_blue
      DB_PORT: 3306
    ports:
      - "8001:8000"
    depends_on:
      - db_blue

  db_blue:
    image: mysql:5.7
    container_name: db_blue
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passdb0127
      MYSQL_DATABASE: all_tables
    ports:
      - "3307:3306"
    volumes:
      - db_data_blue:/var/lib/mysql

  # 🟩 FRONTEND - Green
  frontend_green:
    image: junaiddocker743/greenx-frontend:latest
    container_name: frontend_green
    ports:
      - "3002:3000"   # Green alag port par chalega
    depends_on:
      - backend_green

  # 🟩 BACKEND - Green
  backend_green:
    image: junaiddocker743/greenx-backend:latest
    container_name: backend_green
    environment:
      ENV: dev
      DB: mysql
      DB_USER: root
      DB_PASSWORD: passdb0127
      DB_HOST: db_green
      DB_PORT: 3306
    ports:
      - "8002:8000"
    depends_on:
      - db_green

  db_green:
    image: mysql:5.7
    container_name: db_green
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passdb0127
      MYSQL_DATABASE: all_tables
    ports:
      - "3308:3306"
    volumes:
      - db_data_green:/var/lib/mysql

  # 🔀 Reverse Proxy (Traffic Switch)
  proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend_blue
      - frontend_green

volumes:
  db_data_blue:
  db_data_green:







